version: '2'

services:
  wordpress:
    build:
      context: .
      dockerfile: ./compose/local/Dockerfile
    depends_on:
      - mysql
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DEBUG: 'true'
    volumes:
      - ./wp-content:/var/www/html/wp-content
      - ./plugins:/var/www/html/plugins
      - ./themes:/var/www/html/themes
      - ./compose/local/wp-config.d:/var/www/html/wp-config.d
      - ./compose/local/htaccess:/var/www/html/.htaccess
  mysql:
    image: mariadb:10.2
    volumes:
      - ./mariadb_data:/var/lib/mysql
      - ./compose/local/data:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: therootpassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
